### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Larkin-man** [Larkin-man/TES-parser#2]
- [ ] То - пошире
- [x] 	Строка (считать ее) - выводит плохие символы и возм слишком долго
- [x] 	реинтерпрет - доделай чтоб понятнее
- [ ] 0 пропуск не надо
- [x] 	тес чтение
- [ ] норм если одна строка
- [ ] шов хедер инфром 
- [ ] повторное нажатие на сортровку
- [x] 	find DELE - нажал и зависло
- [x]	иконку опен сав
- [x]	уменьши высоту немного
- [x] 	иконку другую
- [x] 	даблклик на строке - го
- [x] 	сейв
- [x] 	открыть без эдит
- [x] 	иконка
- [x] 	подсчет тегов
- [x] open - save disable
- [x]	СЦЕЛЛ()?
- [x]	клик на таблице - баг
- [x] 	парсир
- [x] СДЕЛАЙ ПОИСК С ТЕКУЩЕЙ ПОЗИЦИИ
- [x]	сплиттер
- [x] 	размеры таблиц изменен если выделить все то край убирается
- [x] 	открываешь большой файл потом малый и баг
- [x] FmAP header карта мира видимое ее изображение хранится в пикселах. плагины сохраняются
- [x]	это карта мира, не локальная!!!
- [x] 	SPLM это эффекты. но не баг блока магии. не знак
- [x]	REFR header координаты игрока ДА. баг тгм некаста. не фракции. ???статы начитеренные к оригиналу и все навыки
- [x] 	NPC& player это не инвентарь и не фракции не статы не спелы не эффекты
- [x] 	сделай проверку эти 12 байт МАИН
- [ ] ридонли
- [x]	у меня всякая дрисня после второго опен хранится
- [x]	ИЗМЕНЕНИЯ КОЛИЧЕСТВА ЗАПИСЕЙ
- [ ] чето с интом в переменных 
- [x] 	открыл шадовармор спавниться но оне финдед
- [x]	GMDT
- [x] 	тут плохо с go потом читать субхедер - читается выбранный субхетер а не go
- [x]	если чекорд 1 то ниче
- [x] 	ТЕСТОВОЕ ПОЛЕ - выводит лишнего много
- [x]	добавь Ф6 как в @той# {самой} 
- [x]	лент изовер 9000 - хотя 9 пусть выведет
- [x]	CSV  как медит
- [x]	кнопка delete когда del2
- [ ] нажал финднекст поле оут исчезло и подвисло немного
- [x]	оффсет шире
- [x]	с секрет  в обле и других
- [ ] мб груп разобрать первые текст
- [ ] то мастер
- [x] 	если открыть обло шадовармор а потом ч классес то баг
- [ ] еще раз проверка переоткр
- [x] 	next и read одно поле
- [x]	экпорт говна . без таб сцв и говно строчное аромор
- [ ] оффсет в 16
- [x]	вроде считать 2 байта не считывает (там пустота)
- [x]	русск в types.txt
- [ ] float to str фиксированный вывод
- [ ] другие проги
- [x] 	поле типа не вмещается
- [x] в скайрим файлах баги
- [ ] ВЕРТИКал попроще нажатие скролинг
